// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: p.proto

package org.xlattice.xlReg;

public final class XLRegProtos {
  private XLRegProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface XLRegMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional .reg.XLRegMsg.Tag Op = 1;
    boolean hasOp();
    org.xlattice.xlReg.XLRegProtos.XLRegMsg.Tag getOp();
    
    // optional bytes AesIV = 2;
    boolean hasAesIV();
    com.google.protobuf.ByteString getAesIV();
    
    // optional bytes AesKey = 3;
    boolean hasAesKey();
    com.google.protobuf.ByteString getAesKey();
    
    // optional bytes Salt1 = 4;
    boolean hasSalt1();
    com.google.protobuf.ByteString getSalt1();
    
    // optional bytes Salt2 = 5;
    boolean hasSalt2();
    com.google.protobuf.ByteString getSalt2();
    
    // optional uint32 Version = 6;
    boolean hasVersion();
    int getVersion();
    
    // optional string ClientName = 8;
    boolean hasClientName();
    String getClientName();
    
    // optional bytes ClientID = 9;
    boolean hasClientID();
    com.google.protobuf.ByteString getClientID();
    
    // optional uint64 ClientAttrs = 10;
    boolean hasClientAttrs();
    long getClientAttrs();
    
    // optional .reg.XLRegMsg.Token ClientSpecs = 11;
    boolean hasClientSpecs();
    org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token getClientSpecs();
    org.xlattice.xlReg.XLRegProtos.XLRegMsg.TokenOrBuilder getClientSpecsOrBuilder();
    
    // optional bytes ClusterID = 13;
    boolean hasClusterID();
    com.google.protobuf.ByteString getClusterID();
    
    // optional string ClusterName = 14;
    boolean hasClusterName();
    String getClusterName();
    
    // optional uint32 ClusterSize = 15;
    boolean hasClusterSize();
    int getClusterSize();
    
    // optional uint64 ClusterAttrs = 16;
    boolean hasClusterAttrs();
    long getClusterAttrs();
    
    // optional uint32 EndPointCount = 17;
    boolean hasEndPointCount();
    int getEndPointCount();
    
    // optional uint64 Which = 20;
    boolean hasWhich();
    long getWhich();
    
    // repeated .reg.XLRegMsg.Token Tokens = 21;
    java.util.List<org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token> 
        getTokensList();
    org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token getTokens(int index);
    int getTokensCount();
    java.util.List<? extends org.xlattice.xlReg.XLRegProtos.XLRegMsg.TokenOrBuilder> 
        getTokensOrBuilderList();
    org.xlattice.xlReg.XLRegProtos.XLRegMsg.TokenOrBuilder getTokensOrBuilder(
        int index);
    
    // optional bytes DigSig = 22;
    boolean hasDigSig();
    com.google.protobuf.ByteString getDigSig();
    
    // optional string ErrDesc = 23;
    boolean hasErrDesc();
    String getErrDesc();
  }
  public static final class XLRegMsg extends
      com.google.protobuf.GeneratedMessage
      implements XLRegMsgOrBuilder {
    // Use XLRegMsg.newBuilder() to construct.
    private XLRegMsg(Builder builder) {
      super(builder);
    }
    private XLRegMsg(boolean noInit) {}
    
    private static final XLRegMsg defaultInstance;
    public static XLRegMsg getDefaultInstance() {
      return defaultInstance;
    }
    
    public XLRegMsg getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.xlattice.xlReg.XLRegProtos.internal_static_reg_XLRegMsg_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.xlattice.xlReg.XLRegProtos.internal_static_reg_XLRegMsg_fieldAccessorTable;
    }
    
    public enum Tag
        implements com.google.protobuf.ProtocolMessageEnum {
      RegCredRequest(0, 1),
      RegCredReply(1, 2),
      Client(2, 3),
      ClientOK(3, 4),
      Create(4, 5),
      CreateReply(5, 6),
      Join(6, 7),
      JoinReply(7, 8),
      GetCluster(8, 9),
      ClusterMembers(9, 10),
      Bye(10, 11),
      Ack(11, 12),
      Error(12, 13),
      ;
      
      public static final int RegCredRequest_VALUE = 1;
      public static final int RegCredReply_VALUE = 2;
      public static final int Client_VALUE = 3;
      public static final int ClientOK_VALUE = 4;
      public static final int Create_VALUE = 5;
      public static final int CreateReply_VALUE = 6;
      public static final int Join_VALUE = 7;
      public static final int JoinReply_VALUE = 8;
      public static final int GetCluster_VALUE = 9;
      public static final int ClusterMembers_VALUE = 10;
      public static final int Bye_VALUE = 11;
      public static final int Ack_VALUE = 12;
      public static final int Error_VALUE = 13;
      
      
      public final int getNumber() { return value; }
      
      public static Tag valueOf(int value) {
        switch (value) {
          case 1: return RegCredRequest;
          case 2: return RegCredReply;
          case 3: return Client;
          case 4: return ClientOK;
          case 5: return Create;
          case 6: return CreateReply;
          case 7: return Join;
          case 8: return JoinReply;
          case 9: return GetCluster;
          case 10: return ClusterMembers;
          case 11: return Bye;
          case 12: return Ack;
          case 13: return Error;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Tag>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Tag>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Tag>() {
              public Tag findValueByNumber(int number) {
                return Tag.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.xlattice.xlReg.XLRegProtos.XLRegMsg.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final Tag[] VALUES = {
        RegCredRequest, RegCredReply, Client, ClientOK, Create, CreateReply, Join, JoinReply, GetCluster, ClusterMembers, Bye, Ack, Error, 
      };
      
      public static Tag valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private Tag(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:reg.XLRegMsg.Tag)
    }
    
    public interface TokenOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
      
      // optional string Name = 1;
      boolean hasName();
      String getName();
      
      // optional uint64 Attrs = 2;
      boolean hasAttrs();
      long getAttrs();
      
      // optional bytes ID = 3;
      boolean hasID();
      com.google.protobuf.ByteString getID();
      
      // optional bytes CommsKey = 4;
      boolean hasCommsKey();
      com.google.protobuf.ByteString getCommsKey();
      
      // optional bytes SigKey = 5;
      boolean hasSigKey();
      com.google.protobuf.ByteString getSigKey();
      
      // repeated string MyEnds = 6;
      java.util.List<String> getMyEndsList();
      int getMyEndsCount();
      String getMyEnds(int index);
      
      // optional bytes DigSig = 7;
      boolean hasDigSig();
      com.google.protobuf.ByteString getDigSig();
    }
    public static final class Token extends
        com.google.protobuf.GeneratedMessage
        implements TokenOrBuilder {
      // Use Token.newBuilder() to construct.
      private Token(Builder builder) {
        super(builder);
      }
      private Token(boolean noInit) {}
      
      private static final Token defaultInstance;
      public static Token getDefaultInstance() {
        return defaultInstance;
      }
      
      public Token getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.xlattice.xlReg.XLRegProtos.internal_static_reg_XLRegMsg_Token_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.xlattice.xlReg.XLRegProtos.internal_static_reg_XLRegMsg_Token_fieldAccessorTable;
      }
      
      private int bitField0_;
      // optional string Name = 1;
      public static final int NAME_FIELD_NUMBER = 1;
      private java.lang.Object name_;
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (com.google.protobuf.Internal.isValidUtf8(bs)) {
            name_ = s;
          }
          return s;
        }
      }
      private com.google.protobuf.ByteString getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      
      // optional uint64 Attrs = 2;
      public static final int ATTRS_FIELD_NUMBER = 2;
      private long attrs_;
      public boolean hasAttrs() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public long getAttrs() {
        return attrs_;
      }
      
      // optional bytes ID = 3;
      public static final int ID_FIELD_NUMBER = 3;
      private com.google.protobuf.ByteString iD_;
      public boolean hasID() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public com.google.protobuf.ByteString getID() {
        return iD_;
      }
      
      // optional bytes CommsKey = 4;
      public static final int COMMSKEY_FIELD_NUMBER = 4;
      private com.google.protobuf.ByteString commsKey_;
      public boolean hasCommsKey() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public com.google.protobuf.ByteString getCommsKey() {
        return commsKey_;
      }
      
      // optional bytes SigKey = 5;
      public static final int SIGKEY_FIELD_NUMBER = 5;
      private com.google.protobuf.ByteString sigKey_;
      public boolean hasSigKey() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public com.google.protobuf.ByteString getSigKey() {
        return sigKey_;
      }
      
      // repeated string MyEnds = 6;
      public static final int MYENDS_FIELD_NUMBER = 6;
      private com.google.protobuf.LazyStringList myEnds_;
      public java.util.List<String>
          getMyEndsList() {
        return myEnds_;
      }
      public int getMyEndsCount() {
        return myEnds_.size();
      }
      public String getMyEnds(int index) {
        return myEnds_.get(index);
      }
      
      // optional bytes DigSig = 7;
      public static final int DIGSIG_FIELD_NUMBER = 7;
      private com.google.protobuf.ByteString digSig_;
      public boolean hasDigSig() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public com.google.protobuf.ByteString getDigSig() {
        return digSig_;
      }
      
      private void initFields() {
        name_ = "";
        attrs_ = 0L;
        iD_ = com.google.protobuf.ByteString.EMPTY;
        commsKey_ = com.google.protobuf.ByteString.EMPTY;
        sigKey_ = com.google.protobuf.ByteString.EMPTY;
        myEnds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        digSig_ = com.google.protobuf.ByteString.EMPTY;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeUInt64(2, attrs_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeBytes(3, iD_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeBytes(4, commsKey_);
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          output.writeBytes(5, sigKey_);
        }
        for (int i = 0; i < myEnds_.size(); i++) {
          output.writeBytes(6, myEnds_.getByteString(i));
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          output.writeBytes(7, digSig_);
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt64Size(2, attrs_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(3, iD_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(4, commsKey_);
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(5, sigKey_);
        }
        {
          int dataSize = 0;
          for (int i = 0; i < myEnds_.size(); i++) {
            dataSize += com.google.protobuf.CodedOutputStream
              .computeBytesSizeNoTag(myEnds_.getByteString(i));
          }
          size += dataSize;
          size += 1 * getMyEndsList().size();
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(7, digSig_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements org.xlattice.xlReg.XLRegProtos.XLRegMsg.TokenOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return org.xlattice.xlReg.XLRegProtos.internal_static_reg_XLRegMsg_Token_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return org.xlattice.xlReg.XLRegProtos.internal_static_reg_XLRegMsg_Token_fieldAccessorTable;
        }
        
        // Construct using org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          name_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          attrs_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000002);
          iD_ = com.google.protobuf.ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000004);
          commsKey_ = com.google.protobuf.ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000008);
          sigKey_ = com.google.protobuf.ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000010);
          myEnds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000020);
          digSig_ = com.google.protobuf.ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000040);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token.getDescriptor();
        }
        
        public org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token getDefaultInstanceForType() {
          return org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token.getDefaultInstance();
        }
        
        public org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token build() {
          org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token buildPartial() {
          org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token result = new org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.name_ = name_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.attrs_ = attrs_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.iD_ = iD_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.commsKey_ = commsKey_;
          if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
            to_bitField0_ |= 0x00000010;
          }
          result.sigKey_ = sigKey_;
          if (((bitField0_ & 0x00000020) == 0x00000020)) {
            myEnds_ = new com.google.protobuf.UnmodifiableLazyStringList(
                myEnds_);
            bitField0_ = (bitField0_ & ~0x00000020);
          }
          result.myEnds_ = myEnds_;
          if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
            to_bitField0_ |= 0x00000020;
          }
          result.digSig_ = digSig_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token) {
            return mergeFrom((org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token other) {
          if (other == org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token.getDefaultInstance()) return this;
          if (other.hasName()) {
            setName(other.getName());
          }
          if (other.hasAttrs()) {
            setAttrs(other.getAttrs());
          }
          if (other.hasID()) {
            setID(other.getID());
          }
          if (other.hasCommsKey()) {
            setCommsKey(other.getCommsKey());
          }
          if (other.hasSigKey()) {
            setSigKey(other.getSigKey());
          }
          if (!other.myEnds_.isEmpty()) {
            if (myEnds_.isEmpty()) {
              myEnds_ = other.myEnds_;
              bitField0_ = (bitField0_ & ~0x00000020);
            } else {
              ensureMyEndsIsMutable();
              myEnds_.addAll(other.myEnds_);
            }
            onChanged();
          }
          if (other.hasDigSig()) {
            setDigSig(other.getDigSig());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public final boolean isInitialized() {
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                name_ = input.readBytes();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                attrs_ = input.readUInt64();
                break;
              }
              case 26: {
                bitField0_ |= 0x00000004;
                iD_ = input.readBytes();
                break;
              }
              case 34: {
                bitField0_ |= 0x00000008;
                commsKey_ = input.readBytes();
                break;
              }
              case 42: {
                bitField0_ |= 0x00000010;
                sigKey_ = input.readBytes();
                break;
              }
              case 50: {
                ensureMyEndsIsMutable();
                myEnds_.add(input.readBytes());
                break;
              }
              case 58: {
                bitField0_ |= 0x00000040;
                digSig_ = input.readBytes();
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // optional string Name = 1;
        private java.lang.Object name_ = "";
        public boolean hasName() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        public Builder setName(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          name_ = value;
          onChanged();
          return this;
        }
        public Builder clearName() {
          bitField0_ = (bitField0_ & ~0x00000001);
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        void setName(com.google.protobuf.ByteString value) {
          bitField0_ |= 0x00000001;
          name_ = value;
          onChanged();
        }
        
        // optional uint64 Attrs = 2;
        private long attrs_ ;
        public boolean hasAttrs() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        public long getAttrs() {
          return attrs_;
        }
        public Builder setAttrs(long value) {
          bitField0_ |= 0x00000002;
          attrs_ = value;
          onChanged();
          return this;
        }
        public Builder clearAttrs() {
          bitField0_ = (bitField0_ & ~0x00000002);
          attrs_ = 0L;
          onChanged();
          return this;
        }
        
        // optional bytes ID = 3;
        private com.google.protobuf.ByteString iD_ = com.google.protobuf.ByteString.EMPTY;
        public boolean hasID() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        public com.google.protobuf.ByteString getID() {
          return iD_;
        }
        public Builder setID(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          iD_ = value;
          onChanged();
          return this;
        }
        public Builder clearID() {
          bitField0_ = (bitField0_ & ~0x00000004);
          iD_ = getDefaultInstance().getID();
          onChanged();
          return this;
        }
        
        // optional bytes CommsKey = 4;
        private com.google.protobuf.ByteString commsKey_ = com.google.protobuf.ByteString.EMPTY;
        public boolean hasCommsKey() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        public com.google.protobuf.ByteString getCommsKey() {
          return commsKey_;
        }
        public Builder setCommsKey(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
          commsKey_ = value;
          onChanged();
          return this;
        }
        public Builder clearCommsKey() {
          bitField0_ = (bitField0_ & ~0x00000008);
          commsKey_ = getDefaultInstance().getCommsKey();
          onChanged();
          return this;
        }
        
        // optional bytes SigKey = 5;
        private com.google.protobuf.ByteString sigKey_ = com.google.protobuf.ByteString.EMPTY;
        public boolean hasSigKey() {
          return ((bitField0_ & 0x00000010) == 0x00000010);
        }
        public com.google.protobuf.ByteString getSigKey() {
          return sigKey_;
        }
        public Builder setSigKey(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
          sigKey_ = value;
          onChanged();
          return this;
        }
        public Builder clearSigKey() {
          bitField0_ = (bitField0_ & ~0x00000010);
          sigKey_ = getDefaultInstance().getSigKey();
          onChanged();
          return this;
        }
        
        // repeated string MyEnds = 6;
        private com.google.protobuf.LazyStringList myEnds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        private void ensureMyEndsIsMutable() {
          if (!((bitField0_ & 0x00000020) == 0x00000020)) {
            myEnds_ = new com.google.protobuf.LazyStringArrayList(myEnds_);
            bitField0_ |= 0x00000020;
           }
        }
        public java.util.List<String>
            getMyEndsList() {
          return java.util.Collections.unmodifiableList(myEnds_);
        }
        public int getMyEndsCount() {
          return myEnds_.size();
        }
        public String getMyEnds(int index) {
          return myEnds_.get(index);
        }
        public Builder setMyEnds(
            int index, String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureMyEndsIsMutable();
          myEnds_.set(index, value);
          onChanged();
          return this;
        }
        public Builder addMyEnds(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureMyEndsIsMutable();
          myEnds_.add(value);
          onChanged();
          return this;
        }
        public Builder addAllMyEnds(
            java.lang.Iterable<String> values) {
          ensureMyEndsIsMutable();
          super.addAll(values, myEnds_);
          onChanged();
          return this;
        }
        public Builder clearMyEnds() {
          myEnds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000020);
          onChanged();
          return this;
        }
        void addMyEnds(com.google.protobuf.ByteString value) {
          ensureMyEndsIsMutable();
          myEnds_.add(value);
          onChanged();
        }
        
        // optional bytes DigSig = 7;
        private com.google.protobuf.ByteString digSig_ = com.google.protobuf.ByteString.EMPTY;
        public boolean hasDigSig() {
          return ((bitField0_ & 0x00000040) == 0x00000040);
        }
        public com.google.protobuf.ByteString getDigSig() {
          return digSig_;
        }
        public Builder setDigSig(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
          digSig_ = value;
          onChanged();
          return this;
        }
        public Builder clearDigSig() {
          bitField0_ = (bitField0_ & ~0x00000040);
          digSig_ = getDefaultInstance().getDigSig();
          onChanged();
          return this;
        }
        
        // @@protoc_insertion_point(builder_scope:reg.XLRegMsg.Token)
      }
      
      static {
        defaultInstance = new Token(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:reg.XLRegMsg.Token)
    }
    
    private int bitField0_;
    // optional .reg.XLRegMsg.Tag Op = 1;
    public static final int OP_FIELD_NUMBER = 1;
    private org.xlattice.xlReg.XLRegProtos.XLRegMsg.Tag op_;
    public boolean hasOp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public org.xlattice.xlReg.XLRegProtos.XLRegMsg.Tag getOp() {
      return op_;
    }
    
    // optional bytes AesIV = 2;
    public static final int AESIV_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString aesIV_;
    public boolean hasAesIV() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.google.protobuf.ByteString getAesIV() {
      return aesIV_;
    }
    
    // optional bytes AesKey = 3;
    public static final int AESKEY_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString aesKey_;
    public boolean hasAesKey() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public com.google.protobuf.ByteString getAesKey() {
      return aesKey_;
    }
    
    // optional bytes Salt1 = 4;
    public static final int SALT1_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString salt1_;
    public boolean hasSalt1() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public com.google.protobuf.ByteString getSalt1() {
      return salt1_;
    }
    
    // optional bytes Salt2 = 5;
    public static final int SALT2_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString salt2_;
    public boolean hasSalt2() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public com.google.protobuf.ByteString getSalt2() {
      return salt2_;
    }
    
    // optional uint32 Version = 6;
    public static final int VERSION_FIELD_NUMBER = 6;
    private int version_;
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public int getVersion() {
      return version_;
    }
    
    // optional string ClientName = 8;
    public static final int CLIENTNAME_FIELD_NUMBER = 8;
    private java.lang.Object clientName_;
    public boolean hasClientName() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public String getClientName() {
      java.lang.Object ref = clientName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          clientName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getClientNameBytes() {
      java.lang.Object ref = clientName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        clientName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional bytes ClientID = 9;
    public static final int CLIENTID_FIELD_NUMBER = 9;
    private com.google.protobuf.ByteString clientID_;
    public boolean hasClientID() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public com.google.protobuf.ByteString getClientID() {
      return clientID_;
    }
    
    // optional uint64 ClientAttrs = 10;
    public static final int CLIENTATTRS_FIELD_NUMBER = 10;
    private long clientAttrs_;
    public boolean hasClientAttrs() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public long getClientAttrs() {
      return clientAttrs_;
    }
    
    // optional .reg.XLRegMsg.Token ClientSpecs = 11;
    public static final int CLIENTSPECS_FIELD_NUMBER = 11;
    private org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token clientSpecs_;
    public boolean hasClientSpecs() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    public org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token getClientSpecs() {
      return clientSpecs_;
    }
    public org.xlattice.xlReg.XLRegProtos.XLRegMsg.TokenOrBuilder getClientSpecsOrBuilder() {
      return clientSpecs_;
    }
    
    // optional bytes ClusterID = 13;
    public static final int CLUSTERID_FIELD_NUMBER = 13;
    private com.google.protobuf.ByteString clusterID_;
    public boolean hasClusterID() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    public com.google.protobuf.ByteString getClusterID() {
      return clusterID_;
    }
    
    // optional string ClusterName = 14;
    public static final int CLUSTERNAME_FIELD_NUMBER = 14;
    private java.lang.Object clusterName_;
    public boolean hasClusterName() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    public String getClusterName() {
      java.lang.Object ref = clusterName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          clusterName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getClusterNameBytes() {
      java.lang.Object ref = clusterName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        clusterName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional uint32 ClusterSize = 15;
    public static final int CLUSTERSIZE_FIELD_NUMBER = 15;
    private int clusterSize_;
    public boolean hasClusterSize() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    public int getClusterSize() {
      return clusterSize_;
    }
    
    // optional uint64 ClusterAttrs = 16;
    public static final int CLUSTERATTRS_FIELD_NUMBER = 16;
    private long clusterAttrs_;
    public boolean hasClusterAttrs() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    public long getClusterAttrs() {
      return clusterAttrs_;
    }
    
    // optional uint32 EndPointCount = 17;
    public static final int ENDPOINTCOUNT_FIELD_NUMBER = 17;
    private int endPointCount_;
    public boolean hasEndPointCount() {
      return ((bitField0_ & 0x00004000) == 0x00004000);
    }
    public int getEndPointCount() {
      return endPointCount_;
    }
    
    // optional uint64 Which = 20;
    public static final int WHICH_FIELD_NUMBER = 20;
    private long which_;
    public boolean hasWhich() {
      return ((bitField0_ & 0x00008000) == 0x00008000);
    }
    public long getWhich() {
      return which_;
    }
    
    // repeated .reg.XLRegMsg.Token Tokens = 21;
    public static final int TOKENS_FIELD_NUMBER = 21;
    private java.util.List<org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token> tokens_;
    public java.util.List<org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token> getTokensList() {
      return tokens_;
    }
    public java.util.List<? extends org.xlattice.xlReg.XLRegProtos.XLRegMsg.TokenOrBuilder> 
        getTokensOrBuilderList() {
      return tokens_;
    }
    public int getTokensCount() {
      return tokens_.size();
    }
    public org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token getTokens(int index) {
      return tokens_.get(index);
    }
    public org.xlattice.xlReg.XLRegProtos.XLRegMsg.TokenOrBuilder getTokensOrBuilder(
        int index) {
      return tokens_.get(index);
    }
    
    // optional bytes DigSig = 22;
    public static final int DIGSIG_FIELD_NUMBER = 22;
    private com.google.protobuf.ByteString digSig_;
    public boolean hasDigSig() {
      return ((bitField0_ & 0x00010000) == 0x00010000);
    }
    public com.google.protobuf.ByteString getDigSig() {
      return digSig_;
    }
    
    // optional string ErrDesc = 23;
    public static final int ERRDESC_FIELD_NUMBER = 23;
    private java.lang.Object errDesc_;
    public boolean hasErrDesc() {
      return ((bitField0_ & 0x00020000) == 0x00020000);
    }
    public String getErrDesc() {
      java.lang.Object ref = errDesc_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          errDesc_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getErrDescBytes() {
      java.lang.Object ref = errDesc_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        errDesc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      op_ = org.xlattice.xlReg.XLRegProtos.XLRegMsg.Tag.RegCredRequest;
      aesIV_ = com.google.protobuf.ByteString.EMPTY;
      aesKey_ = com.google.protobuf.ByteString.EMPTY;
      salt1_ = com.google.protobuf.ByteString.EMPTY;
      salt2_ = com.google.protobuf.ByteString.EMPTY;
      version_ = 0;
      clientName_ = "";
      clientID_ = com.google.protobuf.ByteString.EMPTY;
      clientAttrs_ = 0L;
      clientSpecs_ = org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token.getDefaultInstance();
      clusterID_ = com.google.protobuf.ByteString.EMPTY;
      clusterName_ = "";
      clusterSize_ = 0;
      clusterAttrs_ = 0L;
      endPointCount_ = 0;
      which_ = 0L;
      tokens_ = java.util.Collections.emptyList();
      digSig_ = com.google.protobuf.ByteString.EMPTY;
      errDesc_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, op_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, aesIV_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, aesKey_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, salt1_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, salt2_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeUInt32(6, version_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(8, getClientNameBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(9, clientID_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeUInt64(10, clientAttrs_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeMessage(11, clientSpecs_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeBytes(13, clusterID_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeBytes(14, getClusterNameBytes());
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeUInt32(15, clusterSize_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeUInt64(16, clusterAttrs_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        output.writeUInt32(17, endPointCount_);
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        output.writeUInt64(20, which_);
      }
      for (int i = 0; i < tokens_.size(); i++) {
        output.writeMessage(21, tokens_.get(i));
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        output.writeBytes(22, digSig_);
      }
      if (((bitField0_ & 0x00020000) == 0x00020000)) {
        output.writeBytes(23, getErrDescBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, op_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, aesIV_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, aesKey_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, salt1_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, salt2_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, version_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getClientNameBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, clientID_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(10, clientAttrs_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(11, clientSpecs_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(13, clusterID_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(14, getClusterNameBytes());
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(15, clusterSize_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(16, clusterAttrs_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(17, endPointCount_);
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(20, which_);
      }
      for (int i = 0; i < tokens_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(21, tokens_.get(i));
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(22, digSig_);
      }
      if (((bitField0_ & 0x00020000) == 0x00020000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(23, getErrDescBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.xlattice.xlReg.XLRegProtos.XLRegMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.xlattice.xlReg.XLRegProtos.XLRegMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.xlattice.xlReg.XLRegProtos.XLRegMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.xlattice.xlReg.XLRegProtos.XLRegMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.xlattice.xlReg.XLRegProtos.XLRegMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.xlattice.xlReg.XLRegProtos.XLRegMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.xlattice.xlReg.XLRegProtos.XLRegMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.xlattice.xlReg.XLRegProtos.XLRegMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.xlattice.xlReg.XLRegProtos.XLRegMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.xlattice.xlReg.XLRegProtos.XLRegMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.xlattice.xlReg.XLRegProtos.XLRegMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.xlattice.xlReg.XLRegProtos.XLRegMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.xlattice.xlReg.XLRegProtos.internal_static_reg_XLRegMsg_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.xlattice.xlReg.XLRegProtos.internal_static_reg_XLRegMsg_fieldAccessorTable;
      }
      
      // Construct using org.xlattice.xlReg.XLRegProtos.XLRegMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getClientSpecsFieldBuilder();
          getTokensFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        op_ = org.xlattice.xlReg.XLRegProtos.XLRegMsg.Tag.RegCredRequest;
        bitField0_ = (bitField0_ & ~0x00000001);
        aesIV_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        aesKey_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        salt1_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        salt2_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        version_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        clientName_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        clientID_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        clientAttrs_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000100);
        if (clientSpecsBuilder_ == null) {
          clientSpecs_ = org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token.getDefaultInstance();
        } else {
          clientSpecsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000200);
        clusterID_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000400);
        clusterName_ = "";
        bitField0_ = (bitField0_ & ~0x00000800);
        clusterSize_ = 0;
        bitField0_ = (bitField0_ & ~0x00001000);
        clusterAttrs_ = 0L;
        bitField0_ = (bitField0_ & ~0x00002000);
        endPointCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00004000);
        which_ = 0L;
        bitField0_ = (bitField0_ & ~0x00008000);
        if (tokensBuilder_ == null) {
          tokens_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00010000);
        } else {
          tokensBuilder_.clear();
        }
        digSig_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00020000);
        errDesc_ = "";
        bitField0_ = (bitField0_ & ~0x00040000);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.xlattice.xlReg.XLRegProtos.XLRegMsg.getDescriptor();
      }
      
      public org.xlattice.xlReg.XLRegProtos.XLRegMsg getDefaultInstanceForType() {
        return org.xlattice.xlReg.XLRegProtos.XLRegMsg.getDefaultInstance();
      }
      
      public org.xlattice.xlReg.XLRegProtos.XLRegMsg build() {
        org.xlattice.xlReg.XLRegProtos.XLRegMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.xlattice.xlReg.XLRegProtos.XLRegMsg buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.xlattice.xlReg.XLRegProtos.XLRegMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.xlattice.xlReg.XLRegProtos.XLRegMsg buildPartial() {
        org.xlattice.xlReg.XLRegProtos.XLRegMsg result = new org.xlattice.xlReg.XLRegProtos.XLRegMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.op_ = op_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.aesIV_ = aesIV_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.aesKey_ = aesKey_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.salt1_ = salt1_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.salt2_ = salt2_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.clientName_ = clientName_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.clientID_ = clientID_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.clientAttrs_ = clientAttrs_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        if (clientSpecsBuilder_ == null) {
          result.clientSpecs_ = clientSpecs_;
        } else {
          result.clientSpecs_ = clientSpecsBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.clusterID_ = clusterID_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.clusterName_ = clusterName_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.clusterSize_ = clusterSize_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.clusterAttrs_ = clusterAttrs_;
        if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
          to_bitField0_ |= 0x00004000;
        }
        result.endPointCount_ = endPointCount_;
        if (((from_bitField0_ & 0x00008000) == 0x00008000)) {
          to_bitField0_ |= 0x00008000;
        }
        result.which_ = which_;
        if (tokensBuilder_ == null) {
          if (((bitField0_ & 0x00010000) == 0x00010000)) {
            tokens_ = java.util.Collections.unmodifiableList(tokens_);
            bitField0_ = (bitField0_ & ~0x00010000);
          }
          result.tokens_ = tokens_;
        } else {
          result.tokens_ = tokensBuilder_.build();
        }
        if (((from_bitField0_ & 0x00020000) == 0x00020000)) {
          to_bitField0_ |= 0x00010000;
        }
        result.digSig_ = digSig_;
        if (((from_bitField0_ & 0x00040000) == 0x00040000)) {
          to_bitField0_ |= 0x00020000;
        }
        result.errDesc_ = errDesc_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.xlattice.xlReg.XLRegProtos.XLRegMsg) {
          return mergeFrom((org.xlattice.xlReg.XLRegProtos.XLRegMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.xlattice.xlReg.XLRegProtos.XLRegMsg other) {
        if (other == org.xlattice.xlReg.XLRegProtos.XLRegMsg.getDefaultInstance()) return this;
        if (other.hasOp()) {
          setOp(other.getOp());
        }
        if (other.hasAesIV()) {
          setAesIV(other.getAesIV());
        }
        if (other.hasAesKey()) {
          setAesKey(other.getAesKey());
        }
        if (other.hasSalt1()) {
          setSalt1(other.getSalt1());
        }
        if (other.hasSalt2()) {
          setSalt2(other.getSalt2());
        }
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasClientName()) {
          setClientName(other.getClientName());
        }
        if (other.hasClientID()) {
          setClientID(other.getClientID());
        }
        if (other.hasClientAttrs()) {
          setClientAttrs(other.getClientAttrs());
        }
        if (other.hasClientSpecs()) {
          mergeClientSpecs(other.getClientSpecs());
        }
        if (other.hasClusterID()) {
          setClusterID(other.getClusterID());
        }
        if (other.hasClusterName()) {
          setClusterName(other.getClusterName());
        }
        if (other.hasClusterSize()) {
          setClusterSize(other.getClusterSize());
        }
        if (other.hasClusterAttrs()) {
          setClusterAttrs(other.getClusterAttrs());
        }
        if (other.hasEndPointCount()) {
          setEndPointCount(other.getEndPointCount());
        }
        if (other.hasWhich()) {
          setWhich(other.getWhich());
        }
        if (tokensBuilder_ == null) {
          if (!other.tokens_.isEmpty()) {
            if (tokens_.isEmpty()) {
              tokens_ = other.tokens_;
              bitField0_ = (bitField0_ & ~0x00010000);
            } else {
              ensureTokensIsMutable();
              tokens_.addAll(other.tokens_);
            }
            onChanged();
          }
        } else {
          if (!other.tokens_.isEmpty()) {
            if (tokensBuilder_.isEmpty()) {
              tokensBuilder_.dispose();
              tokensBuilder_ = null;
              tokens_ = other.tokens_;
              bitField0_ = (bitField0_ & ~0x00010000);
              tokensBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getTokensFieldBuilder() : null;
            } else {
              tokensBuilder_.addAllMessages(other.tokens_);
            }
          }
        }
        if (other.hasDigSig()) {
          setDigSig(other.getDigSig());
        }
        if (other.hasErrDesc()) {
          setErrDesc(other.getErrDesc());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              org.xlattice.xlReg.XLRegProtos.XLRegMsg.Tag value = org.xlattice.xlReg.XLRegProtos.XLRegMsg.Tag.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                op_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              aesIV_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              aesKey_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              salt1_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              salt2_ = input.readBytes();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              version_ = input.readUInt32();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000040;
              clientName_ = input.readBytes();
              break;
            }
            case 74: {
              bitField0_ |= 0x00000080;
              clientID_ = input.readBytes();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000100;
              clientAttrs_ = input.readUInt64();
              break;
            }
            case 90: {
              org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token.Builder subBuilder = org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token.newBuilder();
              if (hasClientSpecs()) {
                subBuilder.mergeFrom(getClientSpecs());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setClientSpecs(subBuilder.buildPartial());
              break;
            }
            case 106: {
              bitField0_ |= 0x00000400;
              clusterID_ = input.readBytes();
              break;
            }
            case 114: {
              bitField0_ |= 0x00000800;
              clusterName_ = input.readBytes();
              break;
            }
            case 120: {
              bitField0_ |= 0x00001000;
              clusterSize_ = input.readUInt32();
              break;
            }
            case 128: {
              bitField0_ |= 0x00002000;
              clusterAttrs_ = input.readUInt64();
              break;
            }
            case 136: {
              bitField0_ |= 0x00004000;
              endPointCount_ = input.readUInt32();
              break;
            }
            case 160: {
              bitField0_ |= 0x00008000;
              which_ = input.readUInt64();
              break;
            }
            case 170: {
              org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token.Builder subBuilder = org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addTokens(subBuilder.buildPartial());
              break;
            }
            case 178: {
              bitField0_ |= 0x00020000;
              digSig_ = input.readBytes();
              break;
            }
            case 186: {
              bitField0_ |= 0x00040000;
              errDesc_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional .reg.XLRegMsg.Tag Op = 1;
      private org.xlattice.xlReg.XLRegProtos.XLRegMsg.Tag op_ = org.xlattice.xlReg.XLRegProtos.XLRegMsg.Tag.RegCredRequest;
      public boolean hasOp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public org.xlattice.xlReg.XLRegProtos.XLRegMsg.Tag getOp() {
        return op_;
      }
      public Builder setOp(org.xlattice.xlReg.XLRegProtos.XLRegMsg.Tag value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        op_ = value;
        onChanged();
        return this;
      }
      public Builder clearOp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        op_ = org.xlattice.xlReg.XLRegProtos.XLRegMsg.Tag.RegCredRequest;
        onChanged();
        return this;
      }
      
      // optional bytes AesIV = 2;
      private com.google.protobuf.ByteString aesIV_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasAesIV() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.google.protobuf.ByteString getAesIV() {
        return aesIV_;
      }
      public Builder setAesIV(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        aesIV_ = value;
        onChanged();
        return this;
      }
      public Builder clearAesIV() {
        bitField0_ = (bitField0_ & ~0x00000002);
        aesIV_ = getDefaultInstance().getAesIV();
        onChanged();
        return this;
      }
      
      // optional bytes AesKey = 3;
      private com.google.protobuf.ByteString aesKey_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasAesKey() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public com.google.protobuf.ByteString getAesKey() {
        return aesKey_;
      }
      public Builder setAesKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        aesKey_ = value;
        onChanged();
        return this;
      }
      public Builder clearAesKey() {
        bitField0_ = (bitField0_ & ~0x00000004);
        aesKey_ = getDefaultInstance().getAesKey();
        onChanged();
        return this;
      }
      
      // optional bytes Salt1 = 4;
      private com.google.protobuf.ByteString salt1_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasSalt1() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public com.google.protobuf.ByteString getSalt1() {
        return salt1_;
      }
      public Builder setSalt1(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        salt1_ = value;
        onChanged();
        return this;
      }
      public Builder clearSalt1() {
        bitField0_ = (bitField0_ & ~0x00000008);
        salt1_ = getDefaultInstance().getSalt1();
        onChanged();
        return this;
      }
      
      // optional bytes Salt2 = 5;
      private com.google.protobuf.ByteString salt2_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasSalt2() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public com.google.protobuf.ByteString getSalt2() {
        return salt2_;
      }
      public Builder setSalt2(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        salt2_ = value;
        onChanged();
        return this;
      }
      public Builder clearSalt2() {
        bitField0_ = (bitField0_ & ~0x00000010);
        salt2_ = getDefaultInstance().getSalt2();
        onChanged();
        return this;
      }
      
      // optional uint32 Version = 6;
      private int version_ ;
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public int getVersion() {
        return version_;
      }
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000020;
        version_ = value;
        onChanged();
        return this;
      }
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000020);
        version_ = 0;
        onChanged();
        return this;
      }
      
      // optional string ClientName = 8;
      private java.lang.Object clientName_ = "";
      public boolean hasClientName() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public String getClientName() {
        java.lang.Object ref = clientName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          clientName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setClientName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        clientName_ = value;
        onChanged();
        return this;
      }
      public Builder clearClientName() {
        bitField0_ = (bitField0_ & ~0x00000040);
        clientName_ = getDefaultInstance().getClientName();
        onChanged();
        return this;
      }
      void setClientName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000040;
        clientName_ = value;
        onChanged();
      }
      
      // optional bytes ClientID = 9;
      private com.google.protobuf.ByteString clientID_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasClientID() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public com.google.protobuf.ByteString getClientID() {
        return clientID_;
      }
      public Builder setClientID(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        clientID_ = value;
        onChanged();
        return this;
      }
      public Builder clearClientID() {
        bitField0_ = (bitField0_ & ~0x00000080);
        clientID_ = getDefaultInstance().getClientID();
        onChanged();
        return this;
      }
      
      // optional uint64 ClientAttrs = 10;
      private long clientAttrs_ ;
      public boolean hasClientAttrs() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public long getClientAttrs() {
        return clientAttrs_;
      }
      public Builder setClientAttrs(long value) {
        bitField0_ |= 0x00000100;
        clientAttrs_ = value;
        onChanged();
        return this;
      }
      public Builder clearClientAttrs() {
        bitField0_ = (bitField0_ & ~0x00000100);
        clientAttrs_ = 0L;
        onChanged();
        return this;
      }
      
      // optional .reg.XLRegMsg.Token ClientSpecs = 11;
      private org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token clientSpecs_ = org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token, org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token.Builder, org.xlattice.xlReg.XLRegProtos.XLRegMsg.TokenOrBuilder> clientSpecsBuilder_;
      public boolean hasClientSpecs() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      public org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token getClientSpecs() {
        if (clientSpecsBuilder_ == null) {
          return clientSpecs_;
        } else {
          return clientSpecsBuilder_.getMessage();
        }
      }
      public Builder setClientSpecs(org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token value) {
        if (clientSpecsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          clientSpecs_ = value;
          onChanged();
        } else {
          clientSpecsBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000200;
        return this;
      }
      public Builder setClientSpecs(
          org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token.Builder builderForValue) {
        if (clientSpecsBuilder_ == null) {
          clientSpecs_ = builderForValue.build();
          onChanged();
        } else {
          clientSpecsBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000200;
        return this;
      }
      public Builder mergeClientSpecs(org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token value) {
        if (clientSpecsBuilder_ == null) {
          if (((bitField0_ & 0x00000200) == 0x00000200) &&
              clientSpecs_ != org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token.getDefaultInstance()) {
            clientSpecs_ =
              org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token.newBuilder(clientSpecs_).mergeFrom(value).buildPartial();
          } else {
            clientSpecs_ = value;
          }
          onChanged();
        } else {
          clientSpecsBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000200;
        return this;
      }
      public Builder clearClientSpecs() {
        if (clientSpecsBuilder_ == null) {
          clientSpecs_ = org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token.getDefaultInstance();
          onChanged();
        } else {
          clientSpecsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }
      public org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token.Builder getClientSpecsBuilder() {
        bitField0_ |= 0x00000200;
        onChanged();
        return getClientSpecsFieldBuilder().getBuilder();
      }
      public org.xlattice.xlReg.XLRegProtos.XLRegMsg.TokenOrBuilder getClientSpecsOrBuilder() {
        if (clientSpecsBuilder_ != null) {
          return clientSpecsBuilder_.getMessageOrBuilder();
        } else {
          return clientSpecs_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token, org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token.Builder, org.xlattice.xlReg.XLRegProtos.XLRegMsg.TokenOrBuilder> 
          getClientSpecsFieldBuilder() {
        if (clientSpecsBuilder_ == null) {
          clientSpecsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token, org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token.Builder, org.xlattice.xlReg.XLRegProtos.XLRegMsg.TokenOrBuilder>(
                  clientSpecs_,
                  getParentForChildren(),
                  isClean());
          clientSpecs_ = null;
        }
        return clientSpecsBuilder_;
      }
      
      // optional bytes ClusterID = 13;
      private com.google.protobuf.ByteString clusterID_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasClusterID() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      public com.google.protobuf.ByteString getClusterID() {
        return clusterID_;
      }
      public Builder setClusterID(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        clusterID_ = value;
        onChanged();
        return this;
      }
      public Builder clearClusterID() {
        bitField0_ = (bitField0_ & ~0x00000400);
        clusterID_ = getDefaultInstance().getClusterID();
        onChanged();
        return this;
      }
      
      // optional string ClusterName = 14;
      private java.lang.Object clusterName_ = "";
      public boolean hasClusterName() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      public String getClusterName() {
        java.lang.Object ref = clusterName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          clusterName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setClusterName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        clusterName_ = value;
        onChanged();
        return this;
      }
      public Builder clearClusterName() {
        bitField0_ = (bitField0_ & ~0x00000800);
        clusterName_ = getDefaultInstance().getClusterName();
        onChanged();
        return this;
      }
      void setClusterName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000800;
        clusterName_ = value;
        onChanged();
      }
      
      // optional uint32 ClusterSize = 15;
      private int clusterSize_ ;
      public boolean hasClusterSize() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      public int getClusterSize() {
        return clusterSize_;
      }
      public Builder setClusterSize(int value) {
        bitField0_ |= 0x00001000;
        clusterSize_ = value;
        onChanged();
        return this;
      }
      public Builder clearClusterSize() {
        bitField0_ = (bitField0_ & ~0x00001000);
        clusterSize_ = 0;
        onChanged();
        return this;
      }
      
      // optional uint64 ClusterAttrs = 16;
      private long clusterAttrs_ ;
      public boolean hasClusterAttrs() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      public long getClusterAttrs() {
        return clusterAttrs_;
      }
      public Builder setClusterAttrs(long value) {
        bitField0_ |= 0x00002000;
        clusterAttrs_ = value;
        onChanged();
        return this;
      }
      public Builder clearClusterAttrs() {
        bitField0_ = (bitField0_ & ~0x00002000);
        clusterAttrs_ = 0L;
        onChanged();
        return this;
      }
      
      // optional uint32 EndPointCount = 17;
      private int endPointCount_ ;
      public boolean hasEndPointCount() {
        return ((bitField0_ & 0x00004000) == 0x00004000);
      }
      public int getEndPointCount() {
        return endPointCount_;
      }
      public Builder setEndPointCount(int value) {
        bitField0_ |= 0x00004000;
        endPointCount_ = value;
        onChanged();
        return this;
      }
      public Builder clearEndPointCount() {
        bitField0_ = (bitField0_ & ~0x00004000);
        endPointCount_ = 0;
        onChanged();
        return this;
      }
      
      // optional uint64 Which = 20;
      private long which_ ;
      public boolean hasWhich() {
        return ((bitField0_ & 0x00008000) == 0x00008000);
      }
      public long getWhich() {
        return which_;
      }
      public Builder setWhich(long value) {
        bitField0_ |= 0x00008000;
        which_ = value;
        onChanged();
        return this;
      }
      public Builder clearWhich() {
        bitField0_ = (bitField0_ & ~0x00008000);
        which_ = 0L;
        onChanged();
        return this;
      }
      
      // repeated .reg.XLRegMsg.Token Tokens = 21;
      private java.util.List<org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token> tokens_ =
        java.util.Collections.emptyList();
      private void ensureTokensIsMutable() {
        if (!((bitField0_ & 0x00010000) == 0x00010000)) {
          tokens_ = new java.util.ArrayList<org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token>(tokens_);
          bitField0_ |= 0x00010000;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token, org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token.Builder, org.xlattice.xlReg.XLRegProtos.XLRegMsg.TokenOrBuilder> tokensBuilder_;
      
      public java.util.List<org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token> getTokensList() {
        if (tokensBuilder_ == null) {
          return java.util.Collections.unmodifiableList(tokens_);
        } else {
          return tokensBuilder_.getMessageList();
        }
      }
      public int getTokensCount() {
        if (tokensBuilder_ == null) {
          return tokens_.size();
        } else {
          return tokensBuilder_.getCount();
        }
      }
      public org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token getTokens(int index) {
        if (tokensBuilder_ == null) {
          return tokens_.get(index);
        } else {
          return tokensBuilder_.getMessage(index);
        }
      }
      public Builder setTokens(
          int index, org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token value) {
        if (tokensBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTokensIsMutable();
          tokens_.set(index, value);
          onChanged();
        } else {
          tokensBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setTokens(
          int index, org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token.Builder builderForValue) {
        if (tokensBuilder_ == null) {
          ensureTokensIsMutable();
          tokens_.set(index, builderForValue.build());
          onChanged();
        } else {
          tokensBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addTokens(org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token value) {
        if (tokensBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTokensIsMutable();
          tokens_.add(value);
          onChanged();
        } else {
          tokensBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addTokens(
          int index, org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token value) {
        if (tokensBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTokensIsMutable();
          tokens_.add(index, value);
          onChanged();
        } else {
          tokensBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addTokens(
          org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token.Builder builderForValue) {
        if (tokensBuilder_ == null) {
          ensureTokensIsMutable();
          tokens_.add(builderForValue.build());
          onChanged();
        } else {
          tokensBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addTokens(
          int index, org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token.Builder builderForValue) {
        if (tokensBuilder_ == null) {
          ensureTokensIsMutable();
          tokens_.add(index, builderForValue.build());
          onChanged();
        } else {
          tokensBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllTokens(
          java.lang.Iterable<? extends org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token> values) {
        if (tokensBuilder_ == null) {
          ensureTokensIsMutable();
          super.addAll(values, tokens_);
          onChanged();
        } else {
          tokensBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearTokens() {
        if (tokensBuilder_ == null) {
          tokens_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00010000);
          onChanged();
        } else {
          tokensBuilder_.clear();
        }
        return this;
      }
      public Builder removeTokens(int index) {
        if (tokensBuilder_ == null) {
          ensureTokensIsMutable();
          tokens_.remove(index);
          onChanged();
        } else {
          tokensBuilder_.remove(index);
        }
        return this;
      }
      public org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token.Builder getTokensBuilder(
          int index) {
        return getTokensFieldBuilder().getBuilder(index);
      }
      public org.xlattice.xlReg.XLRegProtos.XLRegMsg.TokenOrBuilder getTokensOrBuilder(
          int index) {
        if (tokensBuilder_ == null) {
          return tokens_.get(index);  } else {
          return tokensBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends org.xlattice.xlReg.XLRegProtos.XLRegMsg.TokenOrBuilder> 
           getTokensOrBuilderList() {
        if (tokensBuilder_ != null) {
          return tokensBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(tokens_);
        }
      }
      public org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token.Builder addTokensBuilder() {
        return getTokensFieldBuilder().addBuilder(
            org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token.getDefaultInstance());
      }
      public org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token.Builder addTokensBuilder(
          int index) {
        return getTokensFieldBuilder().addBuilder(
            index, org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token.getDefaultInstance());
      }
      public java.util.List<org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token.Builder> 
           getTokensBuilderList() {
        return getTokensFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token, org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token.Builder, org.xlattice.xlReg.XLRegProtos.XLRegMsg.TokenOrBuilder> 
          getTokensFieldBuilder() {
        if (tokensBuilder_ == null) {
          tokensBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token, org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token.Builder, org.xlattice.xlReg.XLRegProtos.XLRegMsg.TokenOrBuilder>(
                  tokens_,
                  ((bitField0_ & 0x00010000) == 0x00010000),
                  getParentForChildren(),
                  isClean());
          tokens_ = null;
        }
        return tokensBuilder_;
      }
      
      // optional bytes DigSig = 22;
      private com.google.protobuf.ByteString digSig_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasDigSig() {
        return ((bitField0_ & 0x00020000) == 0x00020000);
      }
      public com.google.protobuf.ByteString getDigSig() {
        return digSig_;
      }
      public Builder setDigSig(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00020000;
        digSig_ = value;
        onChanged();
        return this;
      }
      public Builder clearDigSig() {
        bitField0_ = (bitField0_ & ~0x00020000);
        digSig_ = getDefaultInstance().getDigSig();
        onChanged();
        return this;
      }
      
      // optional string ErrDesc = 23;
      private java.lang.Object errDesc_ = "";
      public boolean hasErrDesc() {
        return ((bitField0_ & 0x00040000) == 0x00040000);
      }
      public String getErrDesc() {
        java.lang.Object ref = errDesc_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          errDesc_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setErrDesc(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00040000;
        errDesc_ = value;
        onChanged();
        return this;
      }
      public Builder clearErrDesc() {
        bitField0_ = (bitField0_ & ~0x00040000);
        errDesc_ = getDefaultInstance().getErrDesc();
        onChanged();
        return this;
      }
      void setErrDesc(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00040000;
        errDesc_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:reg.XLRegMsg)
    }
    
    static {
      defaultInstance = new XLRegMsg(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:reg.XLRegMsg)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_reg_XLRegMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_reg_XLRegMsg_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_reg_XLRegMsg_Token_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_reg_XLRegMsg_Token_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\007p.proto\022\003reg\"\316\005\n\010XLRegMsg\022\035\n\002Op\030\001 \001(\0162" +
      "\021.reg.XLRegMsg.Tag\022\r\n\005AesIV\030\002 \001(\014\022\016\n\006Aes" +
      "Key\030\003 \001(\014\022\r\n\005Salt1\030\004 \001(\014\022\r\n\005Salt2\030\005 \001(\014\022" +
      "\017\n\007Version\030\006 \001(\r\022\022\n\nClientName\030\010 \001(\t\022\020\n\010" +
      "ClientID\030\t \001(\014\022\023\n\013ClientAttrs\030\n \001(\004\022(\n\013C" +
      "lientSpecs\030\013 \001(\0132\023.reg.XLRegMsg.Token\022\021\n" +
      "\tClusterID\030\r \001(\014\022\023\n\013ClusterName\030\016 \001(\t\022\023\n" +
      "\013ClusterSize\030\017 \001(\r\022\024\n\014ClusterAttrs\030\020 \001(\004" +
      "\022\025\n\rEndPointCount\030\021 \001(\r\022\r\n\005Which\030\024 \001(\004\022#" +
      "\n\006Tokens\030\025 \003(\0132\023.reg.XLRegMsg.Token\022\016\n\006D",
      "igSig\030\026 \001(\014\022\017\n\007ErrDesc\030\027 \001(\t\032r\n\005Token\022\014\n" +
      "\004Name\030\001 \001(\t\022\r\n\005Attrs\030\002 \001(\004\022\n\n\002ID\030\003 \001(\014\022\020" +
      "\n\010CommsKey\030\004 \001(\014\022\016\n\006SigKey\030\005 \001(\014\022\016\n\006MyEn" +
      "ds\030\006 \003(\t\022\016\n\006DigSig\030\007 \001(\014\"\274\001\n\003Tag\022\022\n\016RegC" +
      "redRequest\020\001\022\020\n\014RegCredReply\020\002\022\n\n\006Client" +
      "\020\003\022\014\n\010ClientOK\020\004\022\n\n\006Create\020\005\022\017\n\013CreateRe" +
      "ply\020\006\022\010\n\004Join\020\007\022\r\n\tJoinReply\020\010\022\016\n\nGetClu" +
      "ster\020\t\022\022\n\016ClusterMembers\020\n\022\007\n\003Bye\020\013\022\007\n\003A" +
      "ck\020\014\022\t\n\005Error\020\rB!\n\022org.xlattice.xlRegB\013X" +
      "LRegProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_reg_XLRegMsg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_reg_XLRegMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_reg_XLRegMsg_descriptor,
              new java.lang.String[] { "Op", "AesIV", "AesKey", "Salt1", "Salt2", "Version", "ClientName", "ClientID", "ClientAttrs", "ClientSpecs", "ClusterID", "ClusterName", "ClusterSize", "ClusterAttrs", "EndPointCount", "Which", "Tokens", "DigSig", "ErrDesc", },
              org.xlattice.xlReg.XLRegProtos.XLRegMsg.class,
              org.xlattice.xlReg.XLRegProtos.XLRegMsg.Builder.class);
          internal_static_reg_XLRegMsg_Token_descriptor =
            internal_static_reg_XLRegMsg_descriptor.getNestedTypes().get(0);
          internal_static_reg_XLRegMsg_Token_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_reg_XLRegMsg_Token_descriptor,
              new java.lang.String[] { "Name", "Attrs", "ID", "CommsKey", "SigKey", "MyEnds", "DigSig", },
              org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token.class,
              org.xlattice.xlReg.XLRegProtos.XLRegMsg.Token.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
